/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_pwr_ConvolutionCounter */

#ifndef _Included_pl_pwr_ConvolutionCounter
#define _Included_pl_pwr_ConvolutionCounter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_pwr_ConvolutionCounter
 * Method:    countInCpp
 * Signature: ([[Ljava/lang/Double;[[Ljava/lang/Double;)[[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_pl_pwr_ConvolutionCounter_countInCpp
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
